### ISSUE TITLE
Unable to build site

### ISSUE THREAD

**Issue by mttjj** [JustinAiken/jekyll-gitlab-letsencrypt#2]
I installed the `jekyll-gitlab-letsencrypt` gem (version 0.0.1 is showing up when I run `gem list`). And I added the gem to my `_config.yml` so it looks like this: `gems: [jekyll-paginate, jekyll-gitlab-letsencrypt]` but running `jekyll build` always throws this error. I don't know what I'm doing wrong.

> Dependency Error: Yikes! It looks like you don't have jekyll-gitlab-letsencrypt or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-gitlab-letsencrypt' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 

For reference, I'm using the second method of jekyll plugins mentioned on this page: https://jekyllrb.com/docs/plugins/

Please help and thank you!

**Comment by JustinAiken** [comment]
Do add it to the `Gemfile` under the `jekyll-plugins` group, but don't add it to the `_config`'s gems..

### Gemfile
```ruby
source "https://rubygems.org"

gem 'jekyll'
..

group :jekyll_plugins do
  ...
  gem 'jekyll-gitlab-letsencrypt'
end
```

### _config.yml

```yml
...
# Plugins
gems:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
   ...
  # NO jekyll-gitlab-letsencrypt

...

gitlab-letsencrypt:
  personal_access_token: 'secret'   
  gitlab_repo: 'secret' 
  email: 'secret'        
  ...
```
